### ISSUE TITLE
Hides original log

### ISSUE THREAD

**Issue by xPaw** [tolbertam/mocha-appveyor-reporter#10]
Whenever this reporter is used, it hides all the original test report in the logs for some reason. e.g. If you run it locally, it will only say that APPVEYOR_API_URL is not set, and nothing else.

**Comment by tolbertam** [comment]
Sorry for the super late delay in response.  

Unless I'm misunderstanding the issue,   I think it's because this reporter itself doesn't write anything to stdout.  Using it instead of the default (`spec`) reporter for example would cause nothing to be logged.  What I do is use [`mocha-multi`](https://www.npmjs.com/package/mocha-multi) and set the multi environment variable like so:

```powershell
$env:multi="spec=- mocha-appveyor-reporter=-"
./node_modules/.bin/mocha test/unit -R mocha-multi
```

Alternatively, we could have the reporter print output exactly like the `spec` reporter.  Or maybe create an additional reporter that logs output similar to `spec`.

**Comment by tolbertam** [comment]
Closing, but please reopen if my comment is not adequate.
